// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Common._RMI_ParsingClasses;
import RMI.RMI_Common._RMI_ParsingClasses.*;
import RMI.RMI_Classes.*;
import RMI.AutoCreatedClass.*;
import io.netty.buffer.*;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_motionCharacterCancelSkill extends Table {
  public static flat_motionCharacterCancelSkill getRootAsflat_motionCharacterCancelSkill(ByteBuffer _bb) { return getRootAsflat_motionCharacterCancelSkill(_bb, new flat_motionCharacterCancelSkill()); }
  public static flat_motionCharacterCancelSkill getRootAsflat_motionCharacterCancelSkill(ByteBuffer _bb, flat_motionCharacterCancelSkill obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_motionCharacterCancelSkill __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int characterEntityID() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public flat_SkillInfoData usedSkill() { return usedSkill(new flat_SkillInfoData()); }
  public flat_SkillInfoData usedSkill(flat_SkillInfoData obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createflat_motionCharacterCancelSkill(FlatBufferBuilder builder,
      int characterEntityID,
      int usedSkillOffset) {
    builder.startObject(2);
    flat_motionCharacterCancelSkill.addUsedSkill(builder, usedSkillOffset);
    flat_motionCharacterCancelSkill.addCharacterEntityID(builder, characterEntityID);
    return flat_motionCharacterCancelSkill.endflat_motionCharacterCancelSkill(builder);
  }

  public static void startflat_motionCharacterCancelSkill(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addCharacterEntityID(FlatBufferBuilder builder, int characterEntityID) { builder.addInt(0, characterEntityID, 0); }
  public static void addUsedSkill(FlatBufferBuilder builder, int usedSkillOffset) { builder.addOffset(1, usedSkillOffset, 0); }
  public static int endflat_motionCharacterCancelSkill(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_motionCharacterCancelSkill(FlatBufferBuilder builder,
 motionCharacterCancelSkill data) {
        int usedSkillOffset = flat_SkillInfoData.createflat_SkillInfoData(builder, data.usedSkill);
        return createflat_motionCharacterCancelSkill(builder , data.characterEntityID, usedSkillOffset);
    }

    public static byte[] createflat_motionCharacterCancelSkill(motionCharacterCancelSkill data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_motionCharacterCancelSkill.createflat_motionCharacterCancelSkill(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static motionCharacterCancelSkill getRootAsflat_motionCharacterCancelSkill(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        motionCharacterCancelSkill result = new motionCharacterCancelSkill(flat_motionCharacterCancelSkill.getRootAsflat_motionCharacterCancelSkill( buf ) );
        buf = null;
        return result;
    }

}