// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Common._RMI_ParsingClasses;
import RMI.RMI_Common._RMI_ParsingClasses.*;
import RMI.RMI_Classes.*;
import RMI.AutoCreatedClass.*;
import io.netty.buffer.*;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;
@SuppressWarnings("unused")
public final class flat_broadcastingLoadingProgress extends Table {
  public static flat_broadcastingLoadingProgress getRootAsflat_broadcastingLoadingProgress(ByteBuffer _bb) { return getRootAsflat_broadcastingLoadingProgress(_bb, new flat_broadcastingLoadingProgress()); }
  public static flat_broadcastingLoadingProgress getRootAsflat_broadcastingLoadingProgress(ByteBuffer _bb, flat_broadcastingLoadingProgress obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_broadcastingLoadingProgress __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public flat_LoadingPlayerData loadingPlayerList(int j) { return loadingPlayerList(new flat_LoadingPlayerData(), j); }
  public flat_LoadingPlayerData loadingPlayerList(flat_LoadingPlayerData obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int loadingPlayerListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createflat_broadcastingLoadingProgress(FlatBufferBuilder builder,
      int loadingPlayerListOffset) {
    builder.startObject(1);
    flat_broadcastingLoadingProgress.addLoadingPlayerList(builder, loadingPlayerListOffset);
    return flat_broadcastingLoadingProgress.endflat_broadcastingLoadingProgress(builder);
  }

  public static void startflat_broadcastingLoadingProgress(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addLoadingPlayerList(FlatBufferBuilder builder, int loadingPlayerListOffset) { builder.addOffset(0, loadingPlayerListOffset, 0); }
  public static int createLoadingPlayerListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startLoadingPlayerListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endflat_broadcastingLoadingProgress(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_broadcastingLoadingProgress(FlatBufferBuilder builder,
 broadcastingLoadingProgress data) {
        int size0 = data.loadingPlayerList.size();
        int[] loadingPlayerList_ = new int[size0];
        for (int x = 0; x < size0; x++) {
        LoadingPlayerData aa = data.loadingPlayerList.poll();
        loadingPlayerList_[x] = flat_LoadingPlayerData.createflat_LoadingPlayerData(builder, aa);
        }
        int loadingPlayerListOffset = flat_broadcastingLoadingProgress.createLoadingPlayerListVector(builder, loadingPlayerList_);
        return createflat_broadcastingLoadingProgress(builder , loadingPlayerListOffset);
    }

    public static byte[] createflat_broadcastingLoadingProgress(broadcastingLoadingProgress data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_broadcastingLoadingProgress.createflat_broadcastingLoadingProgress(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static broadcastingLoadingProgress getRootAsflat_broadcastingLoadingProgress(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        broadcastingLoadingProgress result = new broadcastingLoadingProgress(flat_broadcastingLoadingProgress.getRootAsflat_broadcastingLoadingProgress( buf ) );
        buf = null;
        return result;
    }

}