// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Common._RMI_ParsingClasses;
import RMI.RMI_Common._RMI_ParsingClasses.*;
import RMI.RMI_Classes.*;
import RMI.AutoCreatedClass.*;
import io.netty.buffer.*;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_userSucceedStoreUpgradeBuff extends Table {
  public static flat_userSucceedStoreUpgradeBuff getRootAsflat_userSucceedStoreUpgradeBuff(ByteBuffer _bb) { return getRootAsflat_userSucceedStoreUpgradeBuff(_bb, new flat_userSucceedStoreUpgradeBuff()); }
  public static flat_userSucceedStoreUpgradeBuff getRootAsflat_userSucceedStoreUpgradeBuff(ByteBuffer _bb, flat_userSucceedStoreUpgradeBuff obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_userSucceedStoreUpgradeBuff __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public flat_StoreUpgradeBuffSlotData storeUpgradeBuffSlotData() { return storeUpgradeBuffSlotData(new flat_StoreUpgradeBuffSlotData()); }
  public flat_StoreUpgradeBuffSlotData storeUpgradeBuffSlotData(flat_StoreUpgradeBuffSlotData obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createflat_userSucceedStoreUpgradeBuff(FlatBufferBuilder builder,
      int storeUpgradeBuffSlotDataOffset) {
    builder.startObject(1);
    flat_userSucceedStoreUpgradeBuff.addStoreUpgradeBuffSlotData(builder, storeUpgradeBuffSlotDataOffset);
    return flat_userSucceedStoreUpgradeBuff.endflat_userSucceedStoreUpgradeBuff(builder);
  }

  public static void startflat_userSucceedStoreUpgradeBuff(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addStoreUpgradeBuffSlotData(FlatBufferBuilder builder, int storeUpgradeBuffSlotDataOffset) { builder.addOffset(0, storeUpgradeBuffSlotDataOffset, 0); }
  public static int endflat_userSucceedStoreUpgradeBuff(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_userSucceedStoreUpgradeBuff(FlatBufferBuilder builder,
 userSucceedStoreUpgradeBuff data) {
        int storeUpgradeBuffSlotDataOffset = flat_StoreUpgradeBuffSlotData.createflat_StoreUpgradeBuffSlotData(builder, data.storeUpgradeBuffSlotData);
        return createflat_userSucceedStoreUpgradeBuff(builder , storeUpgradeBuffSlotDataOffset);
    }

    public static byte[] createflat_userSucceedStoreUpgradeBuff(userSucceedStoreUpgradeBuff data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_userSucceedStoreUpgradeBuff.createflat_userSucceedStoreUpgradeBuff(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static userSucceedStoreUpgradeBuff getRootAsflat_userSucceedStoreUpgradeBuff(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        userSucceedStoreUpgradeBuff result = new userSucceedStoreUpgradeBuff(flat_userSucceedStoreUpgradeBuff.getRootAsflat_userSucceedStoreUpgradeBuff( buf ) );
        buf = null;
        return result;
    }

}