// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Common._RMI_ParsingClasses;
import RMI.RMI_Common._RMI_ParsingClasses.*;
import RMI.RMI_Classes.*;
import RMI.AutoCreatedClass.*;
import io.netty.buffer.*;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_broadcastingBuffTurretSnapshot extends Table {
  public static flat_broadcastingBuffTurretSnapshot getRootAsflat_broadcastingBuffTurretSnapshot(ByteBuffer _bb) { return getRootAsflat_broadcastingBuffTurretSnapshot(_bb, new flat_broadcastingBuffTurretSnapshot()); }
  public static flat_broadcastingBuffTurretSnapshot getRootAsflat_broadcastingBuffTurretSnapshot(ByteBuffer _bb, flat_broadcastingBuffTurretSnapshot obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_broadcastingBuffTurretSnapshot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public flat_BuffTurretData buffTurretSnapshot(int j) { return buffTurretSnapshot(new flat_BuffTurretData(), j); }
  public flat_BuffTurretData buffTurretSnapshot(flat_BuffTurretData obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int buffTurretSnapshotLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createflat_broadcastingBuffTurretSnapshot(FlatBufferBuilder builder,
      int buffTurretSnapshotOffset) {
    builder.startObject(1);
    flat_broadcastingBuffTurretSnapshot.addBuffTurretSnapshot(builder, buffTurretSnapshotOffset);
    return flat_broadcastingBuffTurretSnapshot.endflat_broadcastingBuffTurretSnapshot(builder);
  }

  public static void startflat_broadcastingBuffTurretSnapshot(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addBuffTurretSnapshot(FlatBufferBuilder builder, int buffTurretSnapshotOffset) { builder.addOffset(0, buffTurretSnapshotOffset, 0); }
  public static int createBuffTurretSnapshotVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startBuffTurretSnapshotVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endflat_broadcastingBuffTurretSnapshot(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_broadcastingBuffTurretSnapshot(FlatBufferBuilder builder,
 broadcastingBuffTurretSnapshot data) {
        int size0 = data.buffTurretSnapshot.size();
        int[] buffTurretSnapshot_ = new int[size0];
        for (int x = 0; x < size0; x++) {
        BuffTurretData aa = data.buffTurretSnapshot.poll();
        buffTurretSnapshot_[x] = flat_BuffTurretData.createflat_BuffTurretData(builder, aa);
        }
        int buffTurretSnapshotOffset = flat_broadcastingBuffTurretSnapshot.createBuffTurretSnapshotVector(builder, buffTurretSnapshot_);
        return createflat_broadcastingBuffTurretSnapshot(builder , buffTurretSnapshotOffset);
    }

    public static byte[] createflat_broadcastingBuffTurretSnapshot(broadcastingBuffTurretSnapshot data) {

        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_broadcastingBuffTurretSnapshot.createflat_broadcastingBuffTurretSnapshot(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static broadcastingBuffTurretSnapshot getRootAsflat_broadcastingBuffTurretSnapshot(byte[] data) {

        ByteBuffer readData = wrap(data);
        broadcastingBuffTurretSnapshot result = new broadcastingBuffTurretSnapshot(flat_broadcastingBuffTurretSnapshot.getRootAsflat_broadcastingBuffTurretSnapshot( readData ) );
        readData = null;
        return result;
    }

}