// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Common._RMI_ParsingClasses;
import RMI.RMI_Common._RMI_ParsingClasses.*;
import RMI.RMI_Classes.*;
import RMI.AutoCreatedClass.*;
import io.netty.buffer.*;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_userFailedInstallBuilding extends Table {
  public static flat_userFailedInstallBuilding getRootAsflat_userFailedInstallBuilding(ByteBuffer _bb) { return getRootAsflat_userFailedInstallBuilding(_bb, new flat_userFailedInstallBuilding()); }
  public static flat_userFailedInstallBuilding getRootAsflat_userFailedInstallBuilding(ByteBuffer _bb, flat_userFailedInstallBuilding obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_userFailedInstallBuilding __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int errorCode() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_userFailedInstallBuilding(FlatBufferBuilder builder,
      int errorCode) {
    builder.startObject(1);
    flat_userFailedInstallBuilding.addErrorCode(builder, errorCode);
    return flat_userFailedInstallBuilding.endflat_userFailedInstallBuilding(builder);
  }

  public static void startflat_userFailedInstallBuilding(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addErrorCode(FlatBufferBuilder builder, int errorCode) { builder.addInt(0, errorCode, 0); }
  public static int endflat_userFailedInstallBuilding(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_userFailedInstallBuilding(FlatBufferBuilder builder,
 userFailedInstallBuilding data) {
        return createflat_userFailedInstallBuilding(builder , data.errorCode);
    }

    public static byte[] createflat_userFailedInstallBuilding(userFailedInstallBuilding data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_userFailedInstallBuilding.createflat_userFailedInstallBuilding(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static userFailedInstallBuilding getRootAsflat_userFailedInstallBuilding(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        userFailedInstallBuilding result = new userFailedInstallBuilding(flat_userFailedInstallBuilding.getRootAsflat_userFailedInstallBuilding( buf ) );
        buf = null;
        return result;
    }

}