// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Common._RMI_ParsingClasses;
import RMI.RMI_Common._RMI_ParsingClasses.*;
import RMI.RMI_Classes.*;
import RMI.AutoCreatedClass.*;
import io.netty.buffer.*;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_createWorldMapSkillObjectEntityInfo extends Table {
  public static flat_createWorldMapSkillObjectEntityInfo getRootAsflat_createWorldMapSkillObjectEntityInfo(ByteBuffer _bb) { return getRootAsflat_createWorldMapSkillObjectEntityInfo(_bb, new flat_createWorldMapSkillObjectEntityInfo()); }
  public static flat_createWorldMapSkillObjectEntityInfo getRootAsflat_createWorldMapSkillObjectEntityInfo(ByteBuffer _bb, flat_createWorldMapSkillObjectEntityInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_createWorldMapSkillObjectEntityInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public flat_SkillObjectData skillObjectList(int j) { return skillObjectList(new flat_SkillObjectData(), j); }
  public flat_SkillObjectData skillObjectList(flat_SkillObjectData obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int skillObjectListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createflat_createWorldMapSkillObjectEntityInfo(FlatBufferBuilder builder,
      int skillObjectListOffset) {
    builder.startObject(1);
    flat_createWorldMapSkillObjectEntityInfo.addSkillObjectList(builder, skillObjectListOffset);
    return flat_createWorldMapSkillObjectEntityInfo.endflat_createWorldMapSkillObjectEntityInfo(builder);
  }

  public static void startflat_createWorldMapSkillObjectEntityInfo(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSkillObjectList(FlatBufferBuilder builder, int skillObjectListOffset) { builder.addOffset(0, skillObjectListOffset, 0); }
  public static int createSkillObjectListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSkillObjectListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endflat_createWorldMapSkillObjectEntityInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_createWorldMapSkillObjectEntityInfo(FlatBufferBuilder builder,
 createWorldMapSkillObjectEntityInfo data) {
        int size0 = data.skillObjectList.size();
        int[] skillObjectList_ = new int[size0];
        for (int x = 0; x < size0; x++) {
        SkillObjectData aa = data.skillObjectList.poll();
        skillObjectList_[x] = flat_SkillObjectData.createflat_SkillObjectData(builder, aa);
        }
        int skillObjectListOffset = flat_createWorldMapSkillObjectEntityInfo.createSkillObjectListVector(builder, skillObjectList_);
        return createflat_createWorldMapSkillObjectEntityInfo(builder , skillObjectListOffset);
    }

    public static byte[] createflat_createWorldMapSkillObjectEntityInfo(createWorldMapSkillObjectEntityInfo data) {
        FlatBufferBuilder fbb = PooledFlatBufferBuilder.DEFAULT.poll();
        fbb.finish(flat_createWorldMapSkillObjectEntityInfo.createflat_createWorldMapSkillObjectEntityInfo(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb.clear(); PooledFlatBufferBuilder.DEFAULT.offer(fbb);
        return result;
    }

    public static createWorldMapSkillObjectEntityInfo getRootAsflat_createWorldMapSkillObjectEntityInfo(byte[] data) {
        ByteBuf readData = PooledByteBufAllocator.DEFAULT.directBuffer(data.length);
        readData.writeBytes(data);
        createWorldMapSkillObjectEntityInfo result = new createWorldMapSkillObjectEntityInfo(flat_createWorldMapSkillObjectEntityInfo.getRootAsflat_createWorldMapSkillObjectEntityInfo( readData.nioBuffer() ) );
        readData.release();
        return result;
    }

}