// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Common._RMI_ParsingClasses;
import RMI.RMI_Common._RMI_ParsingClasses.*;
import RMI.RMI_Classes.*;
import RMI.AutoCreatedClass.*;
import io.netty.buffer.*;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_pickSelectedCharacter extends Table {
  public static flat_pickSelectedCharacter getRootAsflat_pickSelectedCharacter(ByteBuffer _bb) { return getRootAsflat_pickSelectedCharacter(_bb, new flat_pickSelectedCharacter()); }
  public static flat_pickSelectedCharacter getRootAsflat_pickSelectedCharacter(ByteBuffer _bb, flat_pickSelectedCharacter obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_pickSelectedCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String googleIDToken() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer googleIDTokenAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer googleIDTokenInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int characterType() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_pickSelectedCharacter(FlatBufferBuilder builder,
      int googleIDTokenOffset,
      int characterType) {
    builder.startObject(2);
    flat_pickSelectedCharacter.addCharacterType(builder, characterType);
    flat_pickSelectedCharacter.addGoogleIDToken(builder, googleIDTokenOffset);
    return flat_pickSelectedCharacter.endflat_pickSelectedCharacter(builder);
  }

  public static void startflat_pickSelectedCharacter(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addGoogleIDToken(FlatBufferBuilder builder, int googleIDTokenOffset) { builder.addOffset(0, googleIDTokenOffset, 0); }
  public static void addCharacterType(FlatBufferBuilder builder, int characterType) { builder.addInt(1, characterType, 0); }
  public static int endflat_pickSelectedCharacter(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_pickSelectedCharacter(FlatBufferBuilder builder,
 pickSelectedCharacter data) {
        int googleIDTokenOffset = builder.createString(data.googleIDToken);
        return createflat_pickSelectedCharacter(builder , googleIDTokenOffset, data.characterType);
    }

    public static byte[] createflat_pickSelectedCharacter(pickSelectedCharacter data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_pickSelectedCharacter.createflat_pickSelectedCharacter(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static pickSelectedCharacter getRootAsflat_pickSelectedCharacter(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        pickSelectedCharacter result = new pickSelectedCharacter(flat_pickSelectedCharacter.getRootAsflat_pickSelectedCharacter( buf ) );
        buf = null;
        return result;
    }

}