// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Common._RMI_ParsingClasses;
import RMI.RMI_Common._RMI_ParsingClasses.*;
import RMI.RMI_Classes.*;
import RMI.AutoCreatedClass.*;
import io.netty.buffer.*;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_motionMonsterDoAttack extends Table {
  public static flat_motionMonsterDoAttack getRootAsflat_motionMonsterDoAttack(ByteBuffer _bb) { return getRootAsflat_motionMonsterDoAttack(_bb, new flat_motionMonsterDoAttack()); }
  public static flat_motionMonsterDoAttack getRootAsflat_motionMonsterDoAttack(ByteBuffer _bb, flat_motionMonsterDoAttack obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_motionMonsterDoAttack __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int monsterEntityID() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public short targetEntityType() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) : 0; }
  public int targetEntityID() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_motionMonsterDoAttack(FlatBufferBuilder builder,
      int monsterEntityID,
      short targetEntityType,
      int targetEntityID) {
    builder.startObject(3);
    flat_motionMonsterDoAttack.addTargetEntityID(builder, targetEntityID);
    flat_motionMonsterDoAttack.addMonsterEntityID(builder, monsterEntityID);
    flat_motionMonsterDoAttack.addTargetEntityType(builder, targetEntityType);
    return flat_motionMonsterDoAttack.endflat_motionMonsterDoAttack(builder);
  }

  public static void startflat_motionMonsterDoAttack(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addMonsterEntityID(FlatBufferBuilder builder, int monsterEntityID) { builder.addInt(0, monsterEntityID, 0); }
  public static void addTargetEntityType(FlatBufferBuilder builder, short targetEntityType) { builder.addShort(1, targetEntityType, 0); }
  public static void addTargetEntityID(FlatBufferBuilder builder, int targetEntityID) { builder.addInt(2, targetEntityID, 0); }
  public static int endflat_motionMonsterDoAttack(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_motionMonsterDoAttack(FlatBufferBuilder builder,
 motionMonsterDoAttack data) {
        return createflat_motionMonsterDoAttack(builder , data.monsterEntityID, data.targetEntityType, data.targetEntityID);
    }

    public static byte[] createflat_motionMonsterDoAttack(motionMonsterDoAttack data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_motionMonsterDoAttack.createflat_motionMonsterDoAttack(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static motionMonsterDoAttack getRootAsflat_motionMonsterDoAttack(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        motionMonsterDoAttack result = new motionMonsterDoAttack(flat_motionMonsterDoAttack.getRootAsflat_motionMonsterDoAttack( buf ) );
        buf = null;
        return result;
    }

}