// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Common._RMI_ParsingClasses;
import RMI.RMI_Common._RMI_ParsingClasses.*;
import RMI.RMI_Classes.*;
import RMI.AutoCreatedClass.*;
import io.netty.buffer.*;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_pickLogicUserOnSelectedCharacter extends Table {
  public static flat_pickLogicUserOnSelectedCharacter getRootAsflat_pickLogicUserOnSelectedCharacter(ByteBuffer _bb) { return getRootAsflat_pickLogicUserOnSelectedCharacter(_bb, new flat_pickLogicUserOnSelectedCharacter()); }
  public static flat_pickLogicUserOnSelectedCharacter getRootAsflat_pickLogicUserOnSelectedCharacter(ByteBuffer _bb, flat_pickLogicUserOnSelectedCharacter obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_pickLogicUserOnSelectedCharacter __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String googleIDToken() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer googleIDTokenAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer googleIDTokenInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int characterType() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_pickLogicUserOnSelectedCharacter(FlatBufferBuilder builder,
      int googleIDTokenOffset,
      int characterType) {
    builder.startObject(2);
    flat_pickLogicUserOnSelectedCharacter.addCharacterType(builder, characterType);
    flat_pickLogicUserOnSelectedCharacter.addGoogleIDToken(builder, googleIDTokenOffset);
    return flat_pickLogicUserOnSelectedCharacter.endflat_pickLogicUserOnSelectedCharacter(builder);
  }

  public static void startflat_pickLogicUserOnSelectedCharacter(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addGoogleIDToken(FlatBufferBuilder builder, int googleIDTokenOffset) { builder.addOffset(0, googleIDTokenOffset, 0); }
  public static void addCharacterType(FlatBufferBuilder builder, int characterType) { builder.addInt(1, characterType, 0); }
  public static int endflat_pickLogicUserOnSelectedCharacter(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_pickLogicUserOnSelectedCharacter(FlatBufferBuilder builder,
 pickLogicUserOnSelectedCharacter data) {
        int googleIDTokenOffset = builder.createString(data.googleIDToken);
        return createflat_pickLogicUserOnSelectedCharacter(builder , googleIDTokenOffset, data.characterType);
    }

    public static byte[] createflat_pickLogicUserOnSelectedCharacter(pickLogicUserOnSelectedCharacter data) {
        FlatBufferBuilder fbb = PooledFlatBufferBuilder.DEFAULT.poll();
        fbb.finish(flat_pickLogicUserOnSelectedCharacter.createflat_pickLogicUserOnSelectedCharacter(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb.clear(); PooledFlatBufferBuilder.DEFAULT.offer(fbb);
        return result;
    }

    public static pickLogicUserOnSelectedCharacter getRootAsflat_pickLogicUserOnSelectedCharacter(byte[] data) {
        ByteBuf readData = PooledByteBufAllocator.DEFAULT.directBuffer(data.length);
        readData.writeBytes(data);
        pickLogicUserOnSelectedCharacter result = new pickLogicUserOnSelectedCharacter(flat_pickLogicUserOnSelectedCharacter.getRootAsflat_pickLogicUserOnSelectedCharacter( readData.nioBuffer() ) );
        readData.release();
        return result;
    }

}