// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Common._RMI_ParsingClasses;
import RMI.RMI_Common._RMI_ParsingClasses.*;
import RMI.RMI_Classes.*;
import RMI.AutoCreatedClass.*;
import io.netty.buffer.*;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_broadcastingFlyingObjectSnapshot extends Table {
  public static flat_broadcastingFlyingObjectSnapshot getRootAsflat_broadcastingFlyingObjectSnapshot(ByteBuffer _bb) { return getRootAsflat_broadcastingFlyingObjectSnapshot(_bb, new flat_broadcastingFlyingObjectSnapshot()); }
  public static flat_broadcastingFlyingObjectSnapshot getRootAsflat_broadcastingFlyingObjectSnapshot(ByteBuffer _bb, flat_broadcastingFlyingObjectSnapshot obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_broadcastingFlyingObjectSnapshot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public flat_FlyingObjectData flyingObjectSnapshot(int j) { return flyingObjectSnapshot(new flat_FlyingObjectData(), j); }
  public flat_FlyingObjectData flyingObjectSnapshot(flat_FlyingObjectData obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int flyingObjectSnapshotLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createflat_broadcastingFlyingObjectSnapshot(FlatBufferBuilder builder,
      int flyingObjectSnapshotOffset) {
    builder.startObject(1);
    flat_broadcastingFlyingObjectSnapshot.addFlyingObjectSnapshot(builder, flyingObjectSnapshotOffset);
    return flat_broadcastingFlyingObjectSnapshot.endflat_broadcastingFlyingObjectSnapshot(builder);
  }

  public static void startflat_broadcastingFlyingObjectSnapshot(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addFlyingObjectSnapshot(FlatBufferBuilder builder, int flyingObjectSnapshotOffset) { builder.addOffset(0, flyingObjectSnapshotOffset, 0); }
  public static int createFlyingObjectSnapshotVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFlyingObjectSnapshotVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endflat_broadcastingFlyingObjectSnapshot(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_broadcastingFlyingObjectSnapshot(FlatBufferBuilder builder,
 broadcastingFlyingObjectSnapshot data) {
        int size0 = data.flyingObjectSnapshot.size();
        int[] flyingObjectSnapshot_ = new int[size0];
        for (int x = 0; x < size0; x++) {
        FlyingObjectData aa = data.flyingObjectSnapshot.poll();
        flyingObjectSnapshot_[x] = flat_FlyingObjectData.createflat_FlyingObjectData(builder, aa);
        }
        int flyingObjectSnapshotOffset = flat_broadcastingFlyingObjectSnapshot.createFlyingObjectSnapshotVector(builder, flyingObjectSnapshot_);
        return createflat_broadcastingFlyingObjectSnapshot(builder , flyingObjectSnapshotOffset);
    }

    public static byte[] createflat_broadcastingFlyingObjectSnapshot(broadcastingFlyingObjectSnapshot data) {
        FlatBufferBuilder fbb = PooledFlatBufferBuilder.DEFAULT.poll();
        fbb.finish(flat_broadcastingFlyingObjectSnapshot.createflat_broadcastingFlyingObjectSnapshot(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb.clear(); PooledFlatBufferBuilder.DEFAULT.offer(fbb);
        return result;
    }

    public static broadcastingFlyingObjectSnapshot getRootAsflat_broadcastingFlyingObjectSnapshot(byte[] data) {
        ByteBuf readData = PooledByteBufAllocator.DEFAULT.directBuffer(data.length);
        readData.writeBytes(data);
        broadcastingFlyingObjectSnapshot result = new broadcastingFlyingObjectSnapshot(flat_broadcastingFlyingObjectSnapshot.getRootAsflat_broadcastingFlyingObjectSnapshot( readData.nioBuffer() ) );
        readData.release();
        return result;
    }

}