// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Classes.RMI_InitClasses;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_RMI_OverConnectionAnnounce extends Table {
  public static flat_RMI_OverConnectionAnnounce getRootAsflat_RMI_OverConnectionAnnounce(ByteBuffer _bb) { return getRootAsflat_RMI_OverConnectionAnnounce(_bb, new flat_RMI_OverConnectionAnnounce()); }
  public static flat_RMI_OverConnectionAnnounce getRootAsflat_RMI_OverConnectionAnnounce(ByteBuffer _bb, flat_RMI_OverConnectionAnnounce obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_RMI_OverConnectionAnnounce __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int maxConnection() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_RMI_OverConnectionAnnounce(FlatBufferBuilder builder,
      int maxConnection) {
    builder.startObject(1);
    flat_RMI_OverConnectionAnnounce.addMaxConnection(builder, maxConnection);
    return flat_RMI_OverConnectionAnnounce.endflat_RMI_OverConnectionAnnounce(builder);
  }

  public static void startflat_RMI_OverConnectionAnnounce(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addMaxConnection(FlatBufferBuilder builder, int maxConnection) { builder.addInt(0, maxConnection, 0); }
  public static int endflat_RMI_OverConnectionAnnounce(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_RMI_OverConnectionAnnounce(FlatBufferBuilder builder,
 RMI_OverConnectionAnnounce data) {
        return createflat_RMI_OverConnectionAnnounce(builder , data.maxConnection);
    }

    public static byte[] createflat_RMI_OverConnectionAnnounce(RMI_OverConnectionAnnounce data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_RMI_OverConnectionAnnounce.createflat_RMI_OverConnectionAnnounce(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static RMI_OverConnectionAnnounce getRootAsflat_RMI_OverConnectionAnnounce(byte[] data) {
        ByteBuffer readData = ByteBuffer.wrap(data);
        RMI_OverConnectionAnnounce result = new RMI_OverConnectionAnnounce(flat_RMI_OverConnectionAnnounce.getRootAsflat_RMI_OverConnectionAnnounce( readData ) );
        readData = null;
        return result;
    }

}