// automatically generated by the FlatBuffers compiler, do not modify

package RMI.RMI_Classes.RMI_InitClasses;

import RMI.RMI_Classes.PooledFlatBufferBuilder;
import io.netty.buffer.*;
import java.nio.*;
import java.lang.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_RMI_UDP_ConnectionConfirm extends Table {
  public static flat_RMI_UDP_ConnectionConfirm getRootAsflat_RMI_UDP_ConnectionConfirm(ByteBuffer _bb) { return getRootAsflat_RMI_UDP_ConnectionConfirm(_bb, new flat_RMI_UDP_ConnectionConfirm()); }
  public static flat_RMI_UDP_ConnectionConfirm getRootAsflat_RMI_UDP_ConnectionConfirm(ByteBuffer _bb, flat_RMI_UDP_ConnectionConfirm obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_RMI_UDP_ConnectionConfirm __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int checkUDPConnection() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_RMI_UDP_ConnectionConfirm(FlatBufferBuilder builder,
      int checkUDP_Connection) {
    builder.startObject(1);
    flat_RMI_UDP_ConnectionConfirm.addCheckUDPConnection(builder, checkUDP_Connection);
    return flat_RMI_UDP_ConnectionConfirm.endflat_RMI_UDP_ConnectionConfirm(builder);
  }

  public static void startflat_RMI_UDP_ConnectionConfirm(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addCheckUDPConnection(FlatBufferBuilder builder, int checkUDPConnection) { builder.addInt(0, checkUDPConnection, 0); }
  public static int endflat_RMI_UDP_ConnectionConfirm(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_RMI_UDP_ConnectionConfirm(FlatBufferBuilder builder,
 RMI_UDP_ConnectionConfirm data) {
        return createflat_RMI_UDP_ConnectionConfirm(builder , data.checkUDP_Connection);
    }

    public static byte[] createflat_RMI_UDP_ConnectionConfirm(RMI_UDP_ConnectionConfirm data) {
        FlatBufferBuilder fbb = PooledFlatBufferBuilder.DEFAULT.poll();
        fbb.finish(flat_RMI_UDP_ConnectionConfirm.createflat_RMI_UDP_ConnectionConfirm(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb.clear(); PooledFlatBufferBuilder.DEFAULT.offer(fbb);
        return result;
    }

    public static RMI_UDP_ConnectionConfirm getRootAsflat_RMI_UDP_ConnectionConfirm(byte[] data) {
        ByteBuf readData = PooledByteBufAllocator.DEFAULT.directBuffer(data.length);
        readData.writeBytes(data);
        RMI_UDP_ConnectionConfirm result = new RMI_UDP_ConnectionConfirm(flat_RMI_UDP_ConnectionConfirm.getRootAsflat_RMI_UDP_ConnectionConfirm( readData.nioBuffer() ) );
        readData.release();
        return result;
    }

}