// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_pickLogicIsVoipHostReady extends Table {
  public static flat_pickLogicIsVoipHostReady getRootAsflat_pickLogicIsVoipHostReady(ByteBuffer _bb) { return getRootAsflat_pickLogicIsVoipHostReady(_bb, new flat_pickLogicIsVoipHostReady()); }
  public static flat_pickLogicIsVoipHostReady getRootAsflat_pickLogicIsVoipHostReady(ByteBuffer _bb, flat_pickLogicIsVoipHostReady obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_pickLogicIsVoipHostReady __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String googleIDToken() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer googleIDTokenAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer googleIDTokenInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public boolean isVoipHostReady() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createflat_pickLogicIsVoipHostReady(FlatBufferBuilder builder,
      int googleIDTokenOffset,
      boolean isVoipHostReady) {
    builder.startObject(2);
    flat_pickLogicIsVoipHostReady.addGoogleIDToken(builder, googleIDTokenOffset);
    flat_pickLogicIsVoipHostReady.addIsVoipHostReady(builder, isVoipHostReady);
    return flat_pickLogicIsVoipHostReady.endflat_pickLogicIsVoipHostReady(builder);
  }

  public static void startflat_pickLogicIsVoipHostReady(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addGoogleIDToken(FlatBufferBuilder builder, int googleIDTokenOffset) { builder.addOffset(0, googleIDTokenOffset, 0); }
  public static void addIsVoipHostReady(FlatBufferBuilder builder, boolean isVoipHostReady) { builder.addBoolean(1, isVoipHostReady, false); }
  public static int endflat_pickLogicIsVoipHostReady(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_pickLogicIsVoipHostReady(FlatBufferBuilder builder,
 pickLogicIsVoipHostReady data) {
        int googleIDTokenOffset = builder.createString(data.googleIDToken);
        return createflat_pickLogicIsVoipHostReady(builder , googleIDTokenOffset, data.isVoipHostReady);
    }

    public static byte[] createflat_pickLogicIsVoipHostReady(pickLogicIsVoipHostReady data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_pickLogicIsVoipHostReady.createflat_pickLogicIsVoipHostReady(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static pickLogicIsVoipHostReady getRootAsflat_pickLogicIsVoipHostReady(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        pickLogicIsVoipHostReady result = new pickLogicIsVoipHostReady(flat_pickLogicIsVoipHostReady.getRootAsflat_pickLogicIsVoipHostReady( buf ) );
        buf = null;
        return result;
    }

}