// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;

import Network.RMI_Classes.*;
import Network.AutoCreatedClass.*;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_EndWave extends Table {
  public static flat_EndWave getRootAsflat_EndWave(ByteBuffer _bb) { return getRootAsflat_EndWave(_bb, new flat_EndWave()); }
  public static flat_EndWave getRootAsflat_EndWave(ByteBuffer _bb, flat_EndWave obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_EndWave __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int waveCount() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_EndWave(FlatBufferBuilder builder,
      int waveCount) {
    builder.startObject(1);
    flat_EndWave.addWaveCount(builder, waveCount);
    return flat_EndWave.endflat_EndWave(builder);
  }

  public static void startflat_EndWave(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addWaveCount(FlatBufferBuilder builder, int waveCount) { builder.addInt(0, waveCount, 0); }
  public static int endflat_EndWave(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_EndWave(FlatBufferBuilder builder,
 EndWave data) {
        return createflat_EndWave(builder , data.waveCount);
    }

    public static byte[] createflat_EndWave(EndWave data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_EndWave.createflat_EndWave(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static EndWave getRootAsflat_EndWave(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        EndWave result = new EndWave(flat_EndWave.getRootAsflat_EndWave( buf ) );
        buf = null;
        return result;
    }

}