// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;

import Network.RMI_Classes.*;
import Network.AutoCreatedClass.*;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_SkillObjectData extends Table {
  public static flat_SkillObjectData getRootAsflat_SkillObjectData(ByteBuffer _bb) { return getRootAsflat_SkillObjectData(_bb, new flat_SkillObjectData()); }
  public static flat_SkillObjectData getRootAsflat_SkillObjectData(ByteBuffer _bb, flat_SkillObjectData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_SkillObjectData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int entityID() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int team() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public float posX() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float posY() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float posZ() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public int userEntityID() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int createdSkillType() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public float directionX() { int o = __offset(18); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float directionY() { int o = __offset(20); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float directionZ() { int o = __offset(22); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createflat_SkillObjectData(FlatBufferBuilder builder,
      int entityID,
      int team,
      float posX,
      float posY,
      float posZ,
      int userEntityID,
      int createdSkillType,
      float directionX,
      float directionY,
      float directionZ) {
    builder.startObject(10);
    flat_SkillObjectData.addDirectionZ(builder, directionZ);
    flat_SkillObjectData.addDirectionY(builder, directionY);
    flat_SkillObjectData.addDirectionX(builder, directionX);
    flat_SkillObjectData.addCreatedSkillType(builder, createdSkillType);
    flat_SkillObjectData.addUserEntityID(builder, userEntityID);
    flat_SkillObjectData.addPosZ(builder, posZ);
    flat_SkillObjectData.addPosY(builder, posY);
    flat_SkillObjectData.addPosX(builder, posX);
    flat_SkillObjectData.addTeam(builder, team);
    flat_SkillObjectData.addEntityID(builder, entityID);
    return flat_SkillObjectData.endflat_SkillObjectData(builder);
  }

  public static void startflat_SkillObjectData(FlatBufferBuilder builder) { builder.startObject(10); }
  public static void addEntityID(FlatBufferBuilder builder, int entityID) { builder.addInt(0, entityID, 0); }
  public static void addTeam(FlatBufferBuilder builder, int team) { builder.addInt(1, team, 0); }
  public static void addPosX(FlatBufferBuilder builder, float posX) { builder.addFloat(2, posX, 0.0f); }
  public static void addPosY(FlatBufferBuilder builder, float posY) { builder.addFloat(3, posY, 0.0f); }
  public static void addPosZ(FlatBufferBuilder builder, float posZ) { builder.addFloat(4, posZ, 0.0f); }
  public static void addUserEntityID(FlatBufferBuilder builder, int userEntityID) { builder.addInt(5, userEntityID, 0); }
  public static void addCreatedSkillType(FlatBufferBuilder builder, int createdSkillType) { builder.addInt(6, createdSkillType, 0); }
  public static void addDirectionX(FlatBufferBuilder builder, float directionX) { builder.addFloat(7, directionX, 0.0f); }
  public static void addDirectionY(FlatBufferBuilder builder, float directionY) { builder.addFloat(8, directionY, 0.0f); }
  public static void addDirectionZ(FlatBufferBuilder builder, float directionZ) { builder.addFloat(9, directionZ, 0.0f); }
  public static int endflat_SkillObjectData(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_SkillObjectData(FlatBufferBuilder builder,
 SkillObjectData data) {
        return createflat_SkillObjectData(builder , data.entityID, data.team, data.posX, data.posY, data.posZ, data.userEntityID, data.createdSkillType, data.directionX, data.directionY, data.directionZ);
    }

    public static byte[] createflat_SkillObjectData(SkillObjectData data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_SkillObjectData.createflat_SkillObjectData(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static SkillObjectData getRootAsflat_SkillObjectData(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        SkillObjectData result = new SkillObjectData(flat_SkillObjectData.getRootAsflat_SkillObjectData( buf ) );
        buf = null;
        return result;
    }

}