// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;

import Network.RMI_Classes.*;
import Network.AutoCreatedClass.*;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_broadcastingStoreUpgradeBuffList extends Table {
  public static flat_broadcastingStoreUpgradeBuffList getRootAsflat_broadcastingStoreUpgradeBuffList(ByteBuffer _bb) { return getRootAsflat_broadcastingStoreUpgradeBuffList(_bb, new flat_broadcastingStoreUpgradeBuffList()); }
  public static flat_broadcastingStoreUpgradeBuffList getRootAsflat_broadcastingStoreUpgradeBuffList(ByteBuffer _bb, flat_broadcastingStoreUpgradeBuffList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_broadcastingStoreUpgradeBuffList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public flat_StoreUpgradeBuffSlotData storeUpgradeBuffSlotDataList(int j) { return storeUpgradeBuffSlotDataList(new flat_StoreUpgradeBuffSlotData(), j); }
  public flat_StoreUpgradeBuffSlotData storeUpgradeBuffSlotDataList(flat_StoreUpgradeBuffSlotData obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int storeUpgradeBuffSlotDataListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createflat_broadcastingStoreUpgradeBuffList(FlatBufferBuilder builder,
      int storeUpgradeBuffSlotDataListOffset) {
    builder.startObject(1);
    flat_broadcastingStoreUpgradeBuffList.addStoreUpgradeBuffSlotDataList(builder, storeUpgradeBuffSlotDataListOffset);
    return flat_broadcastingStoreUpgradeBuffList.endflat_broadcastingStoreUpgradeBuffList(builder);
  }

  public static void startflat_broadcastingStoreUpgradeBuffList(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addStoreUpgradeBuffSlotDataList(FlatBufferBuilder builder, int storeUpgradeBuffSlotDataListOffset) { builder.addOffset(0, storeUpgradeBuffSlotDataListOffset, 0); }
  public static int createStoreUpgradeBuffSlotDataListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startStoreUpgradeBuffSlotDataListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endflat_broadcastingStoreUpgradeBuffList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_broadcastingStoreUpgradeBuffList(FlatBufferBuilder builder,
 broadcastingStoreUpgradeBuffList data) {
        int size0 = data.storeUpgradeBuffSlotDataList.size();
        int[] storeUpgradeBuffSlotDataList_ = new int[size0];
        for (int x = 0; x < size0; x++) {
        StoreUpgradeBuffSlotData aa = data.storeUpgradeBuffSlotDataList.poll();
        storeUpgradeBuffSlotDataList_[x] = flat_StoreUpgradeBuffSlotData.createflat_StoreUpgradeBuffSlotData(builder, aa);
        }
        int storeUpgradeBuffSlotDataListOffset = flat_broadcastingStoreUpgradeBuffList.createStoreUpgradeBuffSlotDataListVector(builder, storeUpgradeBuffSlotDataList_);
        return createflat_broadcastingStoreUpgradeBuffList(builder , storeUpgradeBuffSlotDataListOffset);
    }

    public static byte[] createflat_broadcastingStoreUpgradeBuffList(broadcastingStoreUpgradeBuffList data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_broadcastingStoreUpgradeBuffList.createflat_broadcastingStoreUpgradeBuffList(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static broadcastingStoreUpgradeBuffList getRootAsflat_broadcastingStoreUpgradeBuffList(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        broadcastingStoreUpgradeBuffList result = new broadcastingStoreUpgradeBuffList(flat_broadcastingStoreUpgradeBuffList.getRootAsflat_broadcastingStoreUpgradeBuffList( buf ) );
        buf = null;
        return result;
    }

}