// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;

import Network.RMI_Classes.*;
import Network.AutoCreatedClass.*;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_userSucceedInstallBuilding extends Table {
  public static flat_userSucceedInstallBuilding getRootAsflat_userSucceedInstallBuilding(ByteBuffer _bb) { return getRootAsflat_userSucceedInstallBuilding(_bb, new flat_userSucceedInstallBuilding()); }
  public static flat_userSucceedInstallBuilding getRootAsflat_userSucceedInstallBuilding(ByteBuffer _bb, flat_userSucceedInstallBuilding obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_userSucceedInstallBuilding __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int builderEntityID() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int buildingType() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_userSucceedInstallBuilding(FlatBufferBuilder builder,
      int builderEntityID,
      int buildingType) {
    builder.startObject(2);
    flat_userSucceedInstallBuilding.addBuildingType(builder, buildingType);
    flat_userSucceedInstallBuilding.addBuilderEntityID(builder, builderEntityID);
    return flat_userSucceedInstallBuilding.endflat_userSucceedInstallBuilding(builder);
  }

  public static void startflat_userSucceedInstallBuilding(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addBuilderEntityID(FlatBufferBuilder builder, int builderEntityID) { builder.addInt(0, builderEntityID, 0); }
  public static void addBuildingType(FlatBufferBuilder builder, int buildingType) { builder.addInt(1, buildingType, 0); }
  public static int endflat_userSucceedInstallBuilding(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_userSucceedInstallBuilding(FlatBufferBuilder builder,
 userSucceedInstallBuilding data) {
        return createflat_userSucceedInstallBuilding(builder , data.builderEntityID, data.buildingType);
    }

    public static byte[] createflat_userSucceedInstallBuilding(userSucceedInstallBuilding data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_userSucceedInstallBuilding.createflat_userSucceedInstallBuilding(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static userSucceedInstallBuilding getRootAsflat_userSucceedInstallBuilding(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        userSucceedInstallBuilding result = new userSucceedInstallBuilding(flat_userSucceedInstallBuilding.getRootAsflat_userSucceedInstallBuilding( buf ) );
        buf = null;
        return result;
    }

}