// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;

import Network.RMI_Classes.*;
import Network.AutoCreatedClass.*;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_createWorldMapCharacterEntityInfo extends Table {
  public static flat_createWorldMapCharacterEntityInfo getRootAsflat_createWorldMapCharacterEntityInfo(ByteBuffer _bb) { return getRootAsflat_createWorldMapCharacterEntityInfo(_bb, new flat_createWorldMapCharacterEntityInfo()); }
  public static flat_createWorldMapCharacterEntityInfo getRootAsflat_createWorldMapCharacterEntityInfo(ByteBuffer _bb, flat_createWorldMapCharacterEntityInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_createWorldMapCharacterEntityInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public flat_CharacterData characterList(int j) { return characterList(new flat_CharacterData(), j); }
  public flat_CharacterData characterList(flat_CharacterData obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int characterListLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createflat_createWorldMapCharacterEntityInfo(FlatBufferBuilder builder,
      int characterListOffset) {
    builder.startObject(1);
    flat_createWorldMapCharacterEntityInfo.addCharacterList(builder, characterListOffset);
    return flat_createWorldMapCharacterEntityInfo.endflat_createWorldMapCharacterEntityInfo(builder);
  }

  public static void startflat_createWorldMapCharacterEntityInfo(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addCharacterList(FlatBufferBuilder builder, int characterListOffset) { builder.addOffset(0, characterListOffset, 0); }
  public static int createCharacterListVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCharacterListVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endflat_createWorldMapCharacterEntityInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_createWorldMapCharacterEntityInfo(FlatBufferBuilder builder,
 createWorldMapCharacterEntityInfo data) {
        int size0 = data.characterList.size();
        int[] characterList_ = new int[size0];
        for (int x = 0; x < size0; x++) {
        CharacterData aa = data.characterList.poll();
        characterList_[x] = flat_CharacterData.createflat_CharacterData(builder, aa);
        }
        int characterListOffset = flat_createWorldMapCharacterEntityInfo.createCharacterListVector(builder, characterList_);
        return createflat_createWorldMapCharacterEntityInfo(builder , characterListOffset);
    }

    public static byte[] createflat_createWorldMapCharacterEntityInfo(createWorldMapCharacterEntityInfo data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_createWorldMapCharacterEntityInfo.createflat_createWorldMapCharacterEntityInfo(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static createWorldMapCharacterEntityInfo getRootAsflat_createWorldMapCharacterEntityInfo(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        createWorldMapCharacterEntityInfo result = new createWorldMapCharacterEntityInfo(flat_createWorldMapCharacterEntityInfo.getRootAsflat_createWorldMapCharacterEntityInfo( buf ) );
        buf = null;
        return result;
    }

}