// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;

import Network.RMI_Classes.*;
import Network.AutoCreatedClass.*;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_userFailedBuyItem extends Table {
  public static flat_userFailedBuyItem getRootAsflat_userFailedBuyItem(ByteBuffer _bb) { return getRootAsflat_userFailedBuyItem(_bb, new flat_userFailedBuyItem()); }
  public static flat_userFailedBuyItem getRootAsflat_userFailedBuyItem(ByteBuffer _bb, flat_userFailedBuyItem obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_userFailedBuyItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int errorCode() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_userFailedBuyItem(FlatBufferBuilder builder,
      int errorCode) {
    builder.startObject(1);
    flat_userFailedBuyItem.addErrorCode(builder, errorCode);
    return flat_userFailedBuyItem.endflat_userFailedBuyItem(builder);
  }

  public static void startflat_userFailedBuyItem(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addErrorCode(FlatBufferBuilder builder, int errorCode) { builder.addInt(0, errorCode, 0); }
  public static int endflat_userFailedBuyItem(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_userFailedBuyItem(FlatBufferBuilder builder,
 userFailedBuyItem data) {
        return createflat_userFailedBuyItem(builder , data.errorCode);
    }

    public static byte[] createflat_userFailedBuyItem(userFailedBuyItem data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_userFailedBuyItem.createflat_userFailedBuyItem(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static userFailedBuyItem getRootAsflat_userFailedBuyItem(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        userFailedBuyItem result = new userFailedBuyItem(flat_userFailedBuyItem.getRootAsflat_userFailedBuyItem( buf ) );
        buf = null;
        return result;
    }

}