// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_loginOK extends Table {
  public static flat_loginOK getRootAsflat_loginOK(ByteBuffer _bb) { return getRootAsflat_loginOK(_bb, new flat_loginOK()); }
  public static flat_loginOK getRootAsflat_loginOK(ByteBuffer _bb, flat_loginOK obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_loginOK __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startflat_loginOK(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endflat_loginOK(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

