// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;

import Network.RMI_Classes.*;
import Network.AutoCreatedClass.*;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_installBarricade extends Table {
  public static flat_installBarricade getRootAsflat_installBarricade(ByteBuffer _bb) { return getRootAsflat_installBarricade(_bb, new flat_installBarricade()); }
  public static flat_installBarricade getRootAsflat_installBarricade(ByteBuffer _bb, flat_installBarricade obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_installBarricade __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int worldMapID() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int userEntityID() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int barricadeType() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int areaNumber() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_installBarricade(FlatBufferBuilder builder,
      int worldMapID,
      int userEntityID,
      int barricadeType,
      int areaNumber) {
    builder.startObject(4);
    flat_installBarricade.addAreaNumber(builder, areaNumber);
    flat_installBarricade.addBarricadeType(builder, barricadeType);
    flat_installBarricade.addUserEntityID(builder, userEntityID);
    flat_installBarricade.addWorldMapID(builder, worldMapID);
    return flat_installBarricade.endflat_installBarricade(builder);
  }

  public static void startflat_installBarricade(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addWorldMapID(FlatBufferBuilder builder, int worldMapID) { builder.addInt(0, worldMapID, 0); }
  public static void addUserEntityID(FlatBufferBuilder builder, int userEntityID) { builder.addInt(1, userEntityID, 0); }
  public static void addBarricadeType(FlatBufferBuilder builder, int barricadeType) { builder.addInt(2, barricadeType, 0); }
  public static void addAreaNumber(FlatBufferBuilder builder, int areaNumber) { builder.addInt(3, areaNumber, 0); }
  public static int endflat_installBarricade(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_installBarricade(FlatBufferBuilder builder,
 installBarricade data) {
        return createflat_installBarricade(builder , data.worldMapID, data.userEntityID, data.barricadeType, data.areaNumber);
    }

    public static byte[] createflat_installBarricade(installBarricade data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_installBarricade.createflat_installBarricade(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static installBarricade getRootAsflat_installBarricade(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        installBarricade result = new installBarricade(flat_installBarricade.getRootAsflat_installBarricade( buf ) );
        buf = null;
        return result;
    }

}