// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;

import Network.RMI_Classes.*;
import Network.AutoCreatedClass.*;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_request_SendChattingMessage extends Table {
  public static flat_request_SendChattingMessage getRootAsflat_request_SendChattingMessage(ByteBuffer _bb) { return getRootAsflat_request_SendChattingMessage(_bb, new flat_request_SendChattingMessage()); }
  public static flat_request_SendChattingMessage getRootAsflat_request_SendChattingMessage(ByteBuffer _bb, flat_request_SendChattingMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_request_SendChattingMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int messageType() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String messageData() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageDataAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer messageDataInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createflat_request_SendChattingMessage(FlatBufferBuilder builder,
      int messageType,
      int messageDataOffset) {
    builder.startObject(2);
    flat_request_SendChattingMessage.addMessageData(builder, messageDataOffset);
    flat_request_SendChattingMessage.addMessageType(builder, messageType);
    return flat_request_SendChattingMessage.endflat_request_SendChattingMessage(builder);
  }

  public static void startflat_request_SendChattingMessage(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addMessageType(FlatBufferBuilder builder, int messageType) { builder.addInt(0, messageType, 0); }
  public static void addMessageData(FlatBufferBuilder builder, int messageDataOffset) { builder.addOffset(1, messageDataOffset, 0); }
  public static int endflat_request_SendChattingMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_request_SendChattingMessage(FlatBufferBuilder builder,
 request_SendChattingMessage data) {
        int messageDataOffset = builder.createString(data.messageData);
        return createflat_request_SendChattingMessage(builder , data.messageType, messageDataOffset);
    }

    public static byte[] createflat_request_SendChattingMessage(request_SendChattingMessage data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_request_SendChattingMessage.createflat_request_SendChattingMessage(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static request_SendChattingMessage getRootAsflat_request_SendChattingMessage(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        request_SendChattingMessage result = new request_SendChattingMessage(flat_request_SendChattingMessage.getRootAsflat_request_SendChattingMessage( buf ) );
        buf = null;
        return result;
    }

}