// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;

import Network.RMI_Classes.*;
import Network.AutoCreatedClass.*;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_response_sessionChannelAllocated extends Table {
  public static flat_response_sessionChannelAllocated getRootAsflat_response_sessionChannelAllocated(ByteBuffer _bb) { return getRootAsflat_response_sessionChannelAllocated(_bb, new flat_response_sessionChannelAllocated()); }
  public static flat_response_sessionChannelAllocated getRootAsflat_response_sessionChannelAllocated(ByteBuffer _bb, flat_response_sessionChannelAllocated obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_response_sessionChannelAllocated __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int channelNum() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public flat_MessageData message() { return message(new flat_MessageData()); }
  public flat_MessageData message(flat_MessageData obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createflat_response_sessionChannelAllocated(FlatBufferBuilder builder,
      int channelNum,
      int messageOffset) {
    builder.startObject(2);
    flat_response_sessionChannelAllocated.addMessage(builder, messageOffset);
    flat_response_sessionChannelAllocated.addChannelNum(builder, channelNum);
    return flat_response_sessionChannelAllocated.endflat_response_sessionChannelAllocated(builder);
  }

  public static void startflat_response_sessionChannelAllocated(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addChannelNum(FlatBufferBuilder builder, int channelNum) { builder.addInt(0, channelNum, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(1, messageOffset, 0); }
  public static int endflat_response_sessionChannelAllocated(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_response_sessionChannelAllocated(FlatBufferBuilder builder,
 response_sessionChannelAllocated data) {
        int messageOffset = flat_MessageData.createflat_MessageData(builder, data.message);
        return createflat_response_sessionChannelAllocated(builder , data.channelNum, messageOffset);
    }

    public static byte[] createflat_response_sessionChannelAllocated(response_sessionChannelAllocated data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_response_sessionChannelAllocated.createflat_response_sessionChannelAllocated(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static response_sessionChannelAllocated getRootAsflat_response_sessionChannelAllocated(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        response_sessionChannelAllocated result = new response_sessionChannelAllocated(flat_response_sessionChannelAllocated.getRootAsflat_response_sessionChannelAllocated( buf ) );
        buf = null;
        return result;
    }

}