// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;
import static java.nio.ByteBuffer.wrap;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_initializeMyselfCharacterInfo extends Table {
  public static flat_initializeMyselfCharacterInfo getRootAsflat_initializeMyselfCharacterInfo(ByteBuffer _bb) { return getRootAsflat_initializeMyselfCharacterInfo(_bb, new flat_initializeMyselfCharacterInfo()); }
  public static flat_initializeMyselfCharacterInfo getRootAsflat_initializeMyselfCharacterInfo(ByteBuffer _bb, flat_initializeMyselfCharacterInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_initializeMyselfCharacterInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ownUserEntityID() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_initializeMyselfCharacterInfo(FlatBufferBuilder builder,
      int ownUserEntityID) {
    builder.startObject(1);
    flat_initializeMyselfCharacterInfo.addOwnUserEntityID(builder, ownUserEntityID);
    return flat_initializeMyselfCharacterInfo.endflat_initializeMyselfCharacterInfo(builder);
  }

  public static void startflat_initializeMyselfCharacterInfo(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addOwnUserEntityID(FlatBufferBuilder builder, int ownUserEntityID) { builder.addInt(0, ownUserEntityID, 0); }
  public static int endflat_initializeMyselfCharacterInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_initializeMyselfCharacterInfo(FlatBufferBuilder builder,
 initializeMyselfCharacterInfo data) {
        return createflat_initializeMyselfCharacterInfo(builder , data.ownUserEntityID);
    }

    public static byte[] createflat_initializeMyselfCharacterInfo(initializeMyselfCharacterInfo data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_initializeMyselfCharacterInfo.createflat_initializeMyselfCharacterInfo(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static initializeMyselfCharacterInfo getRootAsflat_initializeMyselfCharacterInfo(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        initializeMyselfCharacterInfo result = new initializeMyselfCharacterInfo(flat_initializeMyselfCharacterInfo.getRootAsflat_initializeMyselfCharacterInfo( buf ) );
        buf = null;
        return result;
    }

}