// automatically generated by the FlatBuffers compiler, do not modify

package Network.RMI_Common.RMI_ParsingClasses;

import Network.RMI_Classes.*;
import Network.AutoCreatedClass.*;
import io.netty.buffer.*;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class flat_userCharacterRespawn extends Table {
  public static flat_userCharacterRespawn getRootAsflat_userCharacterRespawn(ByteBuffer _bb) { return getRootAsflat_userCharacterRespawn(_bb, new flat_userCharacterRespawn()); }
  public static flat_userCharacterRespawn getRootAsflat_userCharacterRespawn(ByteBuffer _bb, flat_userCharacterRespawn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public flat_userCharacterRespawn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int userEntityID() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createflat_userCharacterRespawn(FlatBufferBuilder builder,
      int userEntityID) {
    builder.startObject(1);
    flat_userCharacterRespawn.addUserEntityID(builder, userEntityID);
    return flat_userCharacterRespawn.endflat_userCharacterRespawn(builder);
  }

  public static void startflat_userCharacterRespawn(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addUserEntityID(FlatBufferBuilder builder, int userEntityID) { builder.addInt(0, userEntityID, 0); }
  public static int endflat_userCharacterRespawn(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
    public static int createflat_userCharacterRespawn(FlatBufferBuilder builder,
 userCharacterRespawn data) {
        return createflat_userCharacterRespawn(builder , data.userEntityID);
    }

    public static byte[] createflat_userCharacterRespawn(userCharacterRespawn data) {
        FlatBufferBuilder fbb = new FlatBufferBuilder();
        fbb.finish(flat_userCharacterRespawn.createflat_userCharacterRespawn(fbb, data));
        byte[] result = fbb.sizedByteArray();
        fbb = null;
        return result;
    }

    public static userCharacterRespawn getRootAsflat_userCharacterRespawn(byte[] data) {
        ByteBuffer buf = ByteBuffer.wrap(data);
        userCharacterRespawn result = new userCharacterRespawn(flat_userCharacterRespawn.getRootAsflat_userCharacterRespawn( buf ) );
        buf = null;
        return result;
    }

}